# Generated by Django 4.2.3 on 2023-07-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
